# Generated by Django 3.0.4 on 2020-05-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Technologie',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.RemoveField(
            model_name='panel',
            name='technology',
        ),
        migrations.AddField(
            model_name='panel',
            name='technology_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='technologie_panneau', to='design.Technology'),
            preserve_default=False,
        ),
    ]
