# Generated by Django 3.0.4 on 2020-05-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20200526_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='panel',
            old_name='opent_circuit_voltage',
            new_name='open_circuit_voltage',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='temperature_factor_current_type',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='temperature_factor_power_type',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='temperature_factor_voltage_type',
        ),
    ]
