# Generated by Django 3.0.4 on 2020-05-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_auto_20200526_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='cell_quantity',
        ),
        migrations.RemoveField(
            model_name='panel',
            name='total_cell_surface',
        ),
        migrations.AlterField(
            model_name='panel',
            name='cell_surface',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name="Surface d'une Cell."),
        ),
        migrations.AlterField(
            model_name='panel',
            name='efficiency',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Rendement'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='length',
            field=models.IntegerField(blank=True, verbose_name='Longueur'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='mpp_current',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Impp'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='mpp_voltage',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Vmpp'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='open_circuit_voltage',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Vco'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='parallel_cell_quantity',
            field=models.IntegerField(blank=True, verbose_name='Cell. en Parallèle'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='power',
            field=models.IntegerField(blank=True, verbose_name='Puissance'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='radiation',
            field=models.IntegerField(blank=True, verbose_name='Rayonnement de référence'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='serial_cell_quantity',
            field=models.IntegerField(blank=True, verbose_name='Cell. en Série'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='short_circuit_current',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Icc'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='surface',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Surface'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='temperature',
            field=models.IntegerField(blank=True, verbose_name='Température de référence'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='temperature_factor_current',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Coeff. de Temp. I'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='temperature_factor_power',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Coeff. de Temp. P'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='temperature_factor_voltage',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Coeff. de Temp. V'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='tolerance',
            field=models.IntegerField(blank=True, verbose_name='Tolérance'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='voltage_max',
            field=models.IntegerField(blank=True, verbose_name='Vmax'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='width',
            field=models.IntegerField(blank=True, verbose_name='Largeur'),
        ),
    ]
