# Generated by Django 3.0.4 on 2020-05-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_auto_20200526_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='efficiency',
        ),
    ]
