# Generated by Django 3.0.4 on 2020-06-12 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_mpp_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Element',
        ),
    ]
