# Generated by Django 3.0.4 on 2020-05-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_remove_panel_surface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='cell_surface',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name="Surface d'une Cell."),
        ),
        migrations.AlterField(
            model_name='panel',
            name='comment',
            field=models.CharField(max_length=1000, verbose_name='Commentaire'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='temperature_factor_current',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='Coeff. de Temp. I'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='temperature_factor_power',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='Coeff. de Temp. P'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='temperature_factor_voltage',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True, verbose_name='Coeff. de Temp. V'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='tolerance',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True, verbose_name='Tolérance'),
        ),
    ]
