# Generated by Django 3.0.4 on 2020-05-26 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_auto_20200526_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature_coefficient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='Coeff. Temp. Type')),
            ],
        ),
        migrations.AddField(
            model_name='panel',
            name='temperature_factor_current_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='temp_coeff_current', to='design.Temperature_coefficient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panel',
            name='temperature_factor_power_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='temp_coeff_power', to='design.Temperature_coefficient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='panel',
            name='temperature_factor_voltage_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='temp_coeff_voltage', to='design.Temperature_coefficient'),
            preserve_default=False,
        ),
    ]
