# Generated by Django 3.0.4 on 2020-05-26 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200526_1758'),
        ('design', '0008_auto_20200526_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roof_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Type de Toît',
            },
        ),
        migrations.CreateModel(
            name='Roofing_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Type de Faîtage',
            },
        ),
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('orientation', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tilt', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.Project')),
                ('roof_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roof_type', to='design.Roof_type')),
                ('roofing_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roofing_type', to='design.Roofing_type')),
            ],
            options={
                'verbose_name': 'Toît',
                'verbose_name_plural': 'Toîts',
            },
        ),
        migrations.CreateModel(
            name='Implantation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_orientation', models.IntegerField(blank=True)),
                ('panel_implantation', models.IntegerField(blank=True)),
                ('vertical_overlapping', models.IntegerField(blank=True)),
                ('horizontal_overlapping', models.IntegerField(blank=True)),
                ('vertical_spacing', models.IntegerField(blank=True)),
                ('horizontal_spacing', models.IntegerField(blank=True)),
                ('distance_top', models.IntegerField(blank=True)),
                ('distance_bottom', models.IntegerField(blank=True)),
                ('distance_left', models.IntegerField(blank=True)),
                ('distance_right', models.IntegerField(blank=True)),
                ('abergement_top', models.IntegerField(blank=True)),
                ('abergement_bottom', models.IntegerField(blank=True)),
                ('abergement_left', models.IntegerField(blank=True)),
                ('abergement_right', models.IntegerField(blank=True)),
                ('roof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='design.Roof')),
            ],
            options={
                'verbose_name': 'Implémentation',
                'verbose_name_plural': 'Implémentations',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('left_distance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bottom_distance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('roof_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roof', to='design.Roof')),
            ],
            options={
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elements',
            },
        ),
    ]
