# Generated by Django 3.0.4 on 2020-05-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0009_element_implantation_roof_roof_type_roofing_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roof',
            old_name='length',
            new_name='bottom_length',
        ),
        migrations.AddField(
            model_name='roof',
            name='top_length',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
