# Generated by Django 3.0.4 on 2020-05-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0010_auto_20200526_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roof_type',
            name='value',
            field=models.CharField(max_length=30, unique=True, verbose_name='Modèle'),
        ),
        migrations.AlterField(
            model_name='roofing_type',
            name='value',
            field=models.CharField(max_length=30, unique=True, verbose_name='Modèle'),
        ),
    ]
