# Generated by Django 3.0.4 on 2020-05-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0011_auto_20200526_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roof',
            name='surface',
        ),
        migrations.AlterField(
            model_name='roof',
            name='bottom_length',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Longueur goutière'),
        ),
        migrations.AlterField(
            model_name='roof',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Hauteur'),
        ),
        migrations.AlterField(
            model_name='roof',
            name='orientation',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Orientation'),
        ),
        migrations.AlterField(
            model_name='roof',
            name='tilt',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Inclinaison'),
        ),
        migrations.AlterField(
            model_name='roof',
            name='top_length',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Longueur faîtage'),
        ),
        migrations.AlterField(
            model_name='roof',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Rampant'),
        ),
        migrations.AlterField(
            model_name='roof_type',
            name='value',
            field=models.CharField(max_length=30, unique=True, verbose_name='Type de toît'),
        ),
        migrations.AlterField(
            model_name='roofing_type',
            name='value',
            field=models.CharField(max_length=30, unique=True, verbose_name='Type de Faîtage'),
        ),
    ]
