# Generated by Django 3.0.4 on 2020-05-26 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0012_auto_20200526_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roof',
            name='bottom_length',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Longueur goutière (b)'),
        ),
        migrations.AlterField(
            model_name='roof',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Hauteur (z)'),
        ),
        migrations.AlterField(
            model_name='roof',
            name='top_length',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Longueur faîtage (d)'),
        ),
        migrations.AlterField(
            model_name='roof',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Rampant (a)'),
        ),
    ]
