# Generated by Django 3.0.4 on 2020-05-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0013_auto_20200526_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roof',
            name='bottom_length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Longueur goutière (b)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roof',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Rampant (a)'),
            preserve_default=False,
        ),
    ]
