# Generated by Django 3.0.4 on 2020-05-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0014_auto_20200527_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roof',
            name='bottom_length',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Longueur goutière (b)'),
        ),
        migrations.AlterField(
            model_name='roof',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Hauteur (z)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roof',
            name='orientation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Orientation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roof',
            name='tilt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Inclinaison'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roof',
            name='top_length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Longueur faîtage (d)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roof',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Rampant (a)'),
        ),
    ]
