# Generated by Django 3.0.4 on 2020-05-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0015_auto_20200527_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, unique=True, verbose_name='Orientation')),
            ],
            options={
                'verbose_name': 'Orientation',
            },
        ),
        migrations.CreateModel(
            name='Pose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, unique=True, verbose_name='Pose')),
            ],
            options={
                'verbose_name': ' Pose',
            },
        ),
    ]
