# Generated by Django 3.0.4 on 2020-05-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0017_auto_20200527_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implantation',
            name='abergement_bottom',
            field=models.IntegerField(blank=True, verbose_name='Abergement bas'),
        ),
        migrations.AlterField(
            model_name='implantation',
            name='abergement_left',
            field=models.IntegerField(blank=True, verbose_name='Abergement gauche'),
        ),
        migrations.AlterField(
            model_name='implantation',
            name='abergement_right',
            field=models.IntegerField(blank=True, verbose_name='Abergement droit'),
        ),
        migrations.AlterField(
            model_name='implantation',
            name='abergement_top',
            field=models.IntegerField(blank=True, verbose_name='Abergement Haut'),
        ),
        migrations.AlterField(
            model_name='implantation',
            name='distance_bottom',
            field=models.IntegerField(blank=True, verbose_name='Distance bas'),
        ),
        migrations.AlterField(
            model_name='implantation',
            name='distance_left',
            field=models.IntegerField(blank=True, verbose_name='Distance gauche'),
        ),
        migrations.AlterField(
            model_name='implantation',
            name='distance_right',
            field=models.IntegerField(blank=True, verbose_name='Distance droite'),
        ),
        migrations.AlterField(
            model_name='implantation',
            name='distance_top',
            field=models.IntegerField(blank=True, verbose_name='Distance haut'),
        ),
        migrations.AlterField(
            model_name='implantation',
            name='horizontal_overlapping',
            field=models.IntegerField(blank=True, verbose_name='Recouvrement horizontal'),
        ),
        migrations.AlterField(
            model_name='implantation',
            name='horizontal_spacing',
            field=models.IntegerField(blank=True, verbose_name='Espacement horizontal'),
        ),
        migrations.AlterField(
            model_name='implantation',
            name='vertical_overlapping',
            field=models.IntegerField(blank=True, verbose_name='Recouvrement vertical'),
        ),
        migrations.AlterField(
            model_name='implantation',
            name='vertical_spacing',
            field=models.IntegerField(blank=True, verbose_name='Espacement vertical'),
        ),
    ]
