# Generated by Django 3.0.4 on 2020-05-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0018_auto_20200527_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='mpp_current',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Impp'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='temperature_factor_current',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='Coeff. de Temp. I'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='temperature_factor_power',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='Coeff. de Temp. P'),
        ),
        migrations.AlterField(
            model_name='panel',
            name='temperature_factor_voltage',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='Coeff. de Temp. V'),
        ),
    ]
