# Generated by Django 3.0.4 on 2020-05-30 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200526_1758'),
        ('design', '0019_auto_20200529_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implantation',
            name='roof_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roof_in_implantation', to='design.Roof'),
        ),
        migrations.CreateModel(
            name='MPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(blank=True, verbose_name='En série')),
                ('parallel', models.IntegerField(blank=True, verbose_name='En parallèle')),
                ('config_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='project.Project')),
            ],
            options={
                'verbose_name': 'MPP',
                'verbose_name_plural': 'MPPs',
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inverter_quantity', models.IntegerField(blank=True, verbose_name="Nombre d'onduleurs")),
                ('inverter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inverter', to='design.Inverter', verbose_name='Onduleur')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_in_config', to='project.Project')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
    ]
