# Generated by Django 3.0.4 on 2020-05-31 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0020_auto_20200530_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roof',
            name='roofing_type_id',
        ),
        migrations.DeleteModel(
            name='Roofing_type',
        ),
    ]
