# Generated by Django 3.0.4 on 2020-05-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0022_auto_20200531_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverter',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True, verbose_name='Commentaire'),
        ),
    ]
