# Generated by Django 3.0.4 on 2020-06-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0023_auto_20200531_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverter',
            name='ac_cabling',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='ac_power_max',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='mpp_string_max',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
