# Generated by Django 3.0.4 on 2020-06-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0024_auto_20200602_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='index',
            field=models.IntegerField(blank=True, default=1, verbose_name='Index configuration'),
            preserve_default=False,
        ),
    ]
