# Generated by Django 3.0.4 on 2020-06-04 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0025_config_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpp',
            name='config_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='design.Config'),
        ),
    ]
