# Generated by Django 3.0.4 on 2020-06-04 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('design', '0026_auto_20200604_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('lat', models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Latitude')),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville', to='design.City', verbose_name='Ville')),
                ('panel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panneau_project', to='design.Panel', verbose_name='Type de panneau')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.AlterField(
            model_name='config',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_in_config', to='design.Project'),
        ),
        migrations.AlterField(
            model_name='roof',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='design.Project'),
        ),
    ]
