# Generated by Django 3.0.4 on 2020-05-22 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('average_temp_january', models.DecimalField(decimal_places=1, max_digits=3)),
                ('average_temp_february', models.DecimalField(decimal_places=1, max_digits=3)),
                ('average_temp_march', models.DecimalField(decimal_places=1, max_digits=3)),
                ('average_temp_april', models.DecimalField(decimal_places=1, max_digits=3)),
                ('average_temp_may', models.DecimalField(decimal_places=1, max_digits=3)),
                ('average_temp_june', models.DecimalField(decimal_places=1, max_digits=3)),
                ('average_temp_july', models.DecimalField(decimal_places=1, max_digits=3)),
                ('average_temp_august', models.DecimalField(decimal_places=1, max_digits=3)),
                ('average_temp_september', models.DecimalField(decimal_places=1, max_digits=3)),
                ('average_temp_october', models.DecimalField(decimal_places=1, max_digits=3)),
                ('average_temp_november', models.DecimalField(decimal_places=1, max_digits=3)),
                ('average_temp_december', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('left_distance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bottom_distance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elements',
            },
        ),
        migrations.CreateModel(
            name='Implantation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_orientation', models.IntegerField(blank=True)),
                ('panel_implantation', models.IntegerField(blank=True)),
                ('vertical_overlapping', models.IntegerField(blank=True)),
                ('horizontal_overlapping', models.IntegerField(blank=True)),
                ('vertical_spacing', models.IntegerField(blank=True)),
                ('horizontal_spacing', models.IntegerField(blank=True)),
                ('distance_top', models.IntegerField(blank=True)),
                ('distance_bottom', models.IntegerField(blank=True)),
                ('distance_left', models.IntegerField(blank=True)),
                ('distance_right', models.IntegerField(blank=True)),
                ('abergement_top', models.IntegerField(blank=True)),
                ('abergement_bottom', models.IntegerField(blank=True)),
                ('abergement_left', models.IntegerField(blank=True)),
                ('abergement_right', models.IntegerField(blank=True)),
            ],
            options={
                'verbose_name': 'Implémentation',
                'verbose_name_plural': 'Implémentations',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('building_type', models.IntegerField(blank=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.City')),
                ('panel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panneau', to='design.Panel')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roofing_type', models.IntegerField(blank=True)),
                ('roof_type', models.IntegerField(blank=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('surface', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('orientation', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('tilt', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.Project')),
            ],
            options={
                'verbose_name': 'Toît',
                'verbose_name_plural': 'Toîts',
            },
        ),
    ]
