# Generated by Django 3.0.4 on 2020-05-22 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='implantation',
            name='roof_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.Roof'),
        ),
        migrations.AddField(
            model_name='element',
            name='roof_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roof', to='project.Roof'),
        ),
    ]
