# Generated by Django 3.0.4 on 2020-05-25 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
        ('project', '0002_auto_20200522_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='average_temp_april',
        ),
        migrations.RemoveField(
            model_name='city',
            name='average_temp_august',
        ),
        migrations.RemoveField(
            model_name='city',
            name='average_temp_december',
        ),
        migrations.RemoveField(
            model_name='city',
            name='average_temp_february',
        ),
        migrations.RemoveField(
            model_name='city',
            name='average_temp_january',
        ),
        migrations.RemoveField(
            model_name='city',
            name='average_temp_july',
        ),
        migrations.RemoveField(
            model_name='city',
            name='average_temp_june',
        ),
        migrations.RemoveField(
            model_name='city',
            name='average_temp_march',
        ),
        migrations.RemoveField(
            model_name='city',
            name='average_temp_may',
        ),
        migrations.RemoveField(
            model_name='city',
            name='average_temp_november',
        ),
        migrations.RemoveField(
            model_name='city',
            name='average_temp_october',
        ),
        migrations.RemoveField(
            model_name='city',
            name='average_temp_september',
        ),
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='lon',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='building_type',
            field=models.IntegerField(blank=True, verbose_name='Type de bâtiment'),
        ),
        migrations.AlterField(
            model_name='project',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville', to='project.City', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='project',
            name='panel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panneau', to='design.Panel', verbose_name='Type de panneau'),
        ),
    ]
