# Generated by Django 3.0.4 on 2020-05-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20200525_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='city',
            name='lon',
            field=models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Longitude'),
        ),
    ]
