# Generated by Django 3.0.4 on 2020-05-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20200526_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implantation',
            name='roof_id',
        ),
        migrations.RemoveField(
            model_name='roof',
            name='project_id',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='Implantation',
        ),
        migrations.DeleteModel(
            name='Roof',
        ),
    ]
