# Generated by Django 3.0.4 on 2020-05-31 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200526_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='building_type',
        ),
    ]
