# Generated by Django 3.0.4 on 2020-06-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_remove_project_building_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='avg_irrad_apr',
            field=models.IntegerField(blank=True, default=0, verbose_name='Irrad Avr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_irrad_aug',
            field=models.IntegerField(blank=True, default=0, verbose_name='Irrad Aou'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_irrad_dec',
            field=models.IntegerField(blank=True, default=0, verbose_name='Irrad Dec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_irrad_feb',
            field=models.IntegerField(blank=True, default=0, verbose_name='Irrad Fev'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_irrad_jan',
            field=models.IntegerField(blank=True, default=0, verbose_name='Irrad Jan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_irrad_jul',
            field=models.IntegerField(blank=True, default=0, verbose_name='Irrad Jui'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_irrad_jun',
            field=models.IntegerField(blank=True, default=0, verbose_name='Irrad Jui'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_irrad_mar',
            field=models.IntegerField(blank=True, default=0, verbose_name='Irrad Mar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_irrad_may',
            field=models.IntegerField(blank=True, default=0, verbose_name='Irrad Mai'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_irrad_nov',
            field=models.IntegerField(blank=True, default=0, verbose_name='Irrad Nov'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_irrad_oct',
            field=models.IntegerField(blank=True, default=0, verbose_name='Irrad Oct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_irrad_sep',
            field=models.IntegerField(blank=True, default=0, verbose_name='Irrad Sep'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_temp_apr',
            field=models.FloatField(default=0, verbose_name='Temp Avr'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_temp_aug',
            field=models.FloatField(default=0, verbose_name='Temp Aou'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_temp_dec',
            field=models.FloatField(default=0, verbose_name='Temp Dec'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_temp_feb',
            field=models.FloatField(default=0, verbose_name='Temp Fev'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_temp_jan',
            field=models.FloatField(default=0, verbose_name='Temp Jan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_temp_jul',
            field=models.FloatField(default=0, verbose_name='Temp Jui'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_temp_jun',
            field=models.FloatField(default=0, verbose_name='Temp Jui'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_temp_mar',
            field=models.FloatField(default=0, verbose_name='Temp Mar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_temp_may',
            field=models.FloatField(default=0, verbose_name='Temp Mai'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_temp_nov',
            field=models.FloatField(default=0, verbose_name='Temp Nov'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_temp_oct',
            field=models.FloatField(default=0, verbose_name='Temp Oct'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='avg_temp_sep',
            field=models.FloatField(default=0, verbose_name='Temp Sep'),
            preserve_default=False,
        ),
    ]
