# Generated by Django 3.0.4 on 2020-06-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200602_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='avg_temp_apr',
            field=models.FloatField(null=True, verbose_name='Temp Avr'),
        ),
        migrations.AlterField(
            model_name='city',
            name='avg_temp_aug',
            field=models.FloatField(null=True, verbose_name='Temp Aou'),
        ),
        migrations.AlterField(
            model_name='city',
            name='avg_temp_dec',
            field=models.FloatField(null=True, verbose_name='Temp Dec'),
        ),
        migrations.AlterField(
            model_name='city',
            name='avg_temp_feb',
            field=models.FloatField(null=True, verbose_name='Temp Fev'),
        ),
        migrations.AlterField(
            model_name='city',
            name='avg_temp_jan',
            field=models.FloatField(null=True, verbose_name='Temp Jan'),
        ),
        migrations.AlterField(
            model_name='city',
            name='avg_temp_jul',
            field=models.FloatField(null=True, verbose_name='Temp Jui'),
        ),
        migrations.AlterField(
            model_name='city',
            name='avg_temp_jun',
            field=models.FloatField(null=True, verbose_name='Temp Jui'),
        ),
        migrations.AlterField(
            model_name='city',
            name='avg_temp_mar',
            field=models.FloatField(null=True, verbose_name='Temp Mar'),
        ),
        migrations.AlterField(
            model_name='city',
            name='avg_temp_may',
            field=models.FloatField(null=True, verbose_name='Temp Mai'),
        ),
        migrations.AlterField(
            model_name='city',
            name='avg_temp_nov',
            field=models.FloatField(null=True, verbose_name='Temp Nov'),
        ),
        migrations.AlterField(
            model_name='city',
            name='avg_temp_oct',
            field=models.FloatField(null=True, verbose_name='Temp Oct'),
        ),
        migrations.AlterField(
            model_name='city',
            name='avg_temp_sep',
            field=models.FloatField(null=True, verbose_name='Temp Sep'),
        ),
    ]
