# Generated by Django 3.0.4 on 2020-06-03 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20200602_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='avg_irrad_apr',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_irrad_aug',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_irrad_dec',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_irrad_feb',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_irrad_jan',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_irrad_jul',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_irrad_jun',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_irrad_mar',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_irrad_may',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_irrad_nov',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_irrad_oct',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_irrad_sep',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_temp_apr',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_temp_aug',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_temp_dec',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_temp_feb',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_temp_jan',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_temp_jul',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_temp_jun',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_temp_mar',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_temp_may',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_temp_nov',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_temp_oct',
        ),
        migrations.RemoveField(
            model_name='city',
            name='avg_temp_sep',
        ),
    ]
